/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Exercise from './model/Exercise';
import ExerciseData from './model/ExerciseData';
import ExerciseExpanded from './model/ExerciseExpanded';
import ExerciseReferencedBy from './model/ExerciseReferencedBy';
import ExerciseReferencedByTrainingunit from './model/ExerciseReferencedByTrainingunit';
import Method from './model/Method';
import MethodExpanded from './model/MethodExpanded';
import MethodExpandedReferences from './model/MethodExpandedReferences';
import MethodExpandedReferencesCovers from './model/MethodExpandedReferencesCovers';
import MethodReferencedBy from './model/MethodReferencedBy';
import MethodReferencedByTrainingunit from './model/MethodReferencedByTrainingunit';
import MethodReferences from './model/MethodReferences';
import Technique from './model/Technique';
import TechniqueExpanded from './model/TechniqueExpanded';
import TechniqueReferencedBy from './model/TechniqueReferencedBy';
import TechniqueReferencedByTrainingunit from './model/TechniqueReferencedByTrainingunit';
import Trainingunit from './model/Trainingunit';
import TrainingunitData from './model/TrainingunitData';
import TrainingunitExpanded from './model/TrainingunitExpanded';
import TrainingunitExpandedReferences from './model/TrainingunitExpandedReferences';
import TrainingunitExpandedReferencesMethods from './model/TrainingunitExpandedReferencesMethods';
import TrainingunitReferencedBy from './model/TrainingunitReferencedBy';
import TrainingunitReferences from './model/TrainingunitReferences';
import DefaultApi from './api/DefaultApi';


/**
* ERROR_UNKNOWN.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MartialartsTracker = require('index'); // See note below*.
* var xxxSvc = new MartialartsTracker.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MartialartsTracker.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MartialartsTracker.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MartialartsTracker.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Exercise model constructor.
     * @property {module:model/Exercise}
     */
    Exercise,

    /**
     * The ExerciseData model constructor.
     * @property {module:model/ExerciseData}
     */
    ExerciseData,

    /**
     * The ExerciseExpanded model constructor.
     * @property {module:model/ExerciseExpanded}
     */
    ExerciseExpanded,

    /**
     * The ExerciseReferencedBy model constructor.
     * @property {module:model/ExerciseReferencedBy}
     */
    ExerciseReferencedBy,

    /**
     * The ExerciseReferencedByTrainingunit model constructor.
     * @property {module:model/ExerciseReferencedByTrainingunit}
     */
    ExerciseReferencedByTrainingunit,

    /**
     * The Method model constructor.
     * @property {module:model/Method}
     */
    Method,

    /**
     * The MethodExpanded model constructor.
     * @property {module:model/MethodExpanded}
     */
    MethodExpanded,

    /**
     * The MethodExpandedReferences model constructor.
     * @property {module:model/MethodExpandedReferences}
     */
    MethodExpandedReferences,

    /**
     * The MethodExpandedReferencesCovers model constructor.
     * @property {module:model/MethodExpandedReferencesCovers}
     */
    MethodExpandedReferencesCovers,

    /**
     * The MethodReferencedBy model constructor.
     * @property {module:model/MethodReferencedBy}
     */
    MethodReferencedBy,

    /**
     * The MethodReferencedByTrainingunit model constructor.
     * @property {module:model/MethodReferencedByTrainingunit}
     */
    MethodReferencedByTrainingunit,

    /**
     * The MethodReferences model constructor.
     * @property {module:model/MethodReferences}
     */
    MethodReferences,

    /**
     * The Technique model constructor.
     * @property {module:model/Technique}
     */
    Technique,

    /**
     * The TechniqueExpanded model constructor.
     * @property {module:model/TechniqueExpanded}
     */
    TechniqueExpanded,

    /**
     * The TechniqueReferencedBy model constructor.
     * @property {module:model/TechniqueReferencedBy}
     */
    TechniqueReferencedBy,

    /**
     * The TechniqueReferencedByTrainingunit model constructor.
     * @property {module:model/TechniqueReferencedByTrainingunit}
     */
    TechniqueReferencedByTrainingunit,

    /**
     * The Trainingunit model constructor.
     * @property {module:model/Trainingunit}
     */
    Trainingunit,

    /**
     * The TrainingunitData model constructor.
     * @property {module:model/TrainingunitData}
     */
    TrainingunitData,

    /**
     * The TrainingunitExpanded model constructor.
     * @property {module:model/TrainingunitExpanded}
     */
    TrainingunitExpanded,

    /**
     * The TrainingunitExpandedReferences model constructor.
     * @property {module:model/TrainingunitExpandedReferences}
     */
    TrainingunitExpandedReferences,

    /**
     * The TrainingunitExpandedReferencesMethods model constructor.
     * @property {module:model/TrainingunitExpandedReferencesMethods}
     */
    TrainingunitExpandedReferencesMethods,

    /**
     * The TrainingunitReferencedBy model constructor.
     * @property {module:model/TrainingunitReferencedBy}
     */
    TrainingunitReferencedBy,

    /**
     * The TrainingunitReferences model constructor.
     * @property {module:model/TrainingunitReferences}
     */
    TrainingunitReferences,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
