FROM node:8.11 as build

ARG API
ARG TOKEN

WORKDIR /usr/src/app/

COPY . .

RUN npm run-script start

FROM danshu93/cordova-android:latest
RUN cordova create /usr/src/cordova com.danshu93.matracker ma-tracker

WORKDIR /usr/src/cordova/

RUN rm -rf ./www/*

COPY --from=build /usr/src/app/build ./www

RUN cordova platform add "android@6.0"

CMD cordova build
