/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ExerciseData model module.
* @module model/ExerciseData
* @version 0.0.1
*/
export default class ExerciseData {
    /**
    * Constructs a new <code>ExerciseData</code>.
    * @alias module:model/ExerciseData
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ExerciseData</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExerciseData} obj Optional instance to populate.
    * @return {module:model/ExerciseData} The populated <code>ExerciseData</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExerciseData();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {String} kind
    */
    kind = undefined;
    /**
    * @member {String} name
    */
    name = undefined;








}


