/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExerciseReferencedByTrainingunit'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExerciseReferencedByTrainingunit'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.ExerciseReferencedBy = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.ExerciseReferencedByTrainingunit);
  }
}(this, function(ApiClient, ExerciseReferencedByTrainingunit) {
  'use strict';




  /**
   * The ExerciseReferencedBy model module.
   * @module model/ExerciseReferencedBy
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ExerciseReferencedBy</code>.
   * @alias module:model/ExerciseReferencedBy
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ExerciseReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExerciseReferencedBy} obj Optional instance to populate.
   * @return {module:model/ExerciseReferencedBy} The populated <code>ExerciseReferencedBy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('trainingunit')) {
        obj['trainingunit'] = ExerciseReferencedByTrainingunit.constructFromObject(data['trainingunit']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ExerciseReferencedByTrainingunit} trainingunit
   */
  exports.prototype['trainingunit'] = undefined;



  return exports;
}));


