/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ExerciseReferencedByTrainingunit from './ExerciseReferencedByTrainingunit';





/**
* The ExerciseReferencedBy model module.
* @module model/ExerciseReferencedBy
* @version 0.0.1
*/
export default class ExerciseReferencedBy {
    /**
    * Constructs a new <code>ExerciseReferencedBy</code>.
    * @alias module:model/ExerciseReferencedBy
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ExerciseReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ExerciseReferencedBy} obj Optional instance to populate.
    * @return {module:model/ExerciseReferencedBy} The populated <code>ExerciseReferencedBy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExerciseReferencedBy();

            
            
            

            if (data.hasOwnProperty('trainingunit')) {
                obj['trainingunit'] = ExerciseReferencedByTrainingunit.constructFromObject(data['trainingunit']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ExerciseReferencedByTrainingunit} trainingunit
    */
    trainingunit = undefined;








}


