/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MethodReferencedByTrainingunit from './MethodReferencedByTrainingunit';





/**
* The MethodReferencedBy model module.
* @module model/MethodReferencedBy
* @version 0.0.1
*/
export default class MethodReferencedBy {
    /**
    * Constructs a new <code>MethodReferencedBy</code>.
    * @alias module:model/MethodReferencedBy
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MethodReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MethodReferencedBy} obj Optional instance to populate.
    * @return {module:model/MethodReferencedBy} The populated <code>MethodReferencedBy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MethodReferencedBy();

            
            
            

            if (data.hasOwnProperty('trainingunit')) {
                obj['trainingunit'] = MethodReferencedByTrainingunit.constructFromObject(data['trainingunit']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MethodReferencedByTrainingunit} trainingunit
    */
    trainingunit = undefined;








}


