/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MethodExpandedReferencesCovers from './MethodExpandedReferencesCovers';





/**
* The MethodExpandedReferences model module.
* @module model/MethodExpandedReferences
* @version 0.0.1
*/
export default class MethodExpandedReferences {
    /**
    * Constructs a new <code>MethodExpandedReferences</code>.
    * @alias module:model/MethodExpandedReferences
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MethodExpandedReferences</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MethodExpandedReferences} obj Optional instance to populate.
    * @return {module:model/MethodExpandedReferences} The populated <code>MethodExpandedReferences</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MethodExpandedReferences();

            
            
            

            if (data.hasOwnProperty('covers')) {
                obj['covers'] = MethodExpandedReferencesCovers.constructFromObject(data['covers']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MethodExpandedReferencesCovers} covers
    */
    covers = undefined;








}


