/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExerciseData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExerciseData'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.MethodExpandedReferencesCovers = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.ExerciseData);
  }
}(this, function(ApiClient, ExerciseData) {
  'use strict';




  /**
   * The MethodExpandedReferencesCovers model module.
   * @module model/MethodExpandedReferencesCovers
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>MethodExpandedReferencesCovers</code>.
   * @alias module:model/MethodExpandedReferencesCovers
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MethodExpandedReferencesCovers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodExpandedReferencesCovers} obj Optional instance to populate.
   * @return {module:model/MethodExpandedReferencesCovers} The populated <code>MethodExpandedReferencesCovers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ExerciseData.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('references')) {
        obj['references'] = ApiClient.convertToType(data['references'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ExerciseData} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Object} references
   */
  exports.prototype['references'] = undefined;



  return exports;
}));


