/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MethodReferences model module.
* @module model/MethodReferences
* @version 0.0.1
*/
export default class MethodReferences {
    /**
    * Constructs a new <code>MethodReferences</code>.
    * @alias module:model/MethodReferences
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MethodReferences</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MethodReferences} obj Optional instance to populate.
    * @return {module:model/MethodReferences} The populated <code>MethodReferences</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MethodReferences();

            
            
            

            if (data.hasOwnProperty('covers')) {
                obj['covers'] = ApiClient.convertToType(data['covers'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} covers
    */
    covers = undefined;








}


