/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MethodExpandedReferencesCovers'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MethodExpandedReferencesCovers'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.MethodExpandedReferences = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.MethodExpandedReferencesCovers);
  }
}(this, function(ApiClient, MethodExpandedReferencesCovers) {
  'use strict';




  /**
   * The MethodExpandedReferences model module.
   * @module model/MethodExpandedReferences
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>MethodExpandedReferences</code>.
   * @alias module:model/MethodExpandedReferences
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>MethodExpandedReferences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MethodExpandedReferences} obj Optional instance to populate.
   * @return {module:model/MethodExpandedReferences} The populated <code>MethodExpandedReferences</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('covers')) {
        obj['covers'] = MethodExpandedReferencesCovers.constructFromObject(data['covers']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MethodExpandedReferencesCovers} covers
   */
  exports.prototype['covers'] = undefined;



  return exports;
}));


