/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MethodReferences', 'model/TechniqueReferencedByTrainingunit'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MethodReferences'), require('./TechniqueReferencedByTrainingunit'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.TechniqueReferencedBy = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.MethodReferences, root.MartialartsTracker.TechniqueReferencedByTrainingunit);
  }
}(this, function(ApiClient, MethodReferences, TechniqueReferencedByTrainingunit) {
  'use strict';




  /**
   * The TechniqueReferencedBy model module.
   * @module model/TechniqueReferencedBy
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TechniqueReferencedBy</code>.
   * @alias module:model/TechniqueReferencedBy
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TechniqueReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TechniqueReferencedBy} obj Optional instance to populate.
   * @return {module:model/TechniqueReferencedBy} The populated <code>TechniqueReferencedBy</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('method')) {
        obj['method'] = MethodReferences.constructFromObject(data['method']);
      }
      if (data.hasOwnProperty('trainingunit')) {
        obj['trainingunit'] = TechniqueReferencedByTrainingunit.constructFromObject(data['trainingunit']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MethodReferences} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {module:model/TechniqueReferencedByTrainingunit} trainingunit
   */
  exports.prototype['trainingunit'] = undefined;



  return exports;
}));


