/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.TechniqueReferencedByTrainingunit = factory(root.MartialartsTracker.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TechniqueReferencedByTrainingunit model module.
   * @module model/TechniqueReferencedByTrainingunit
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TechniqueReferencedByTrainingunit</code>.
   * @alias module:model/TechniqueReferencedByTrainingunit
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>TechniqueReferencedByTrainingunit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TechniqueReferencedByTrainingunit} obj Optional instance to populate.
   * @return {module:model/TechniqueReferencedByTrainingunit} The populated <code>TechniqueReferencedByTrainingunit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('techniques')) {
        obj['techniques'] = ApiClient.convertToType(data['techniques'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} techniques
   */
  exports.prototype['techniques'] = undefined;



  return exports;
}));


