/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MethodReferences from './MethodReferences';
import TechniqueReferencedByTrainingunit from './TechniqueReferencedByTrainingunit';





/**
* The TechniqueReferencedBy model module.
* @module model/TechniqueReferencedBy
* @version 0.0.1
*/
export default class TechniqueReferencedBy {
    /**
    * Constructs a new <code>TechniqueReferencedBy</code>.
    * @alias module:model/TechniqueReferencedBy
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TechniqueReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TechniqueReferencedBy} obj Optional instance to populate.
    * @return {module:model/TechniqueReferencedBy} The populated <code>TechniqueReferencedBy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TechniqueReferencedBy();

            
            
            

            if (data.hasOwnProperty('method')) {
                obj['method'] = MethodReferences.constructFromObject(data['method']);
            }
            if (data.hasOwnProperty('trainingunit')) {
                obj['trainingunit'] = TechniqueReferencedByTrainingunit.constructFromObject(data['trainingunit']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MethodReferences} method
    */
    method = undefined;
    /**
    * @member {module:model/TechniqueReferencedByTrainingunit} trainingunit
    */
    trainingunit = undefined;








}


