/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MethodExpandedReferencesCovers', 'model/TrainingunitExpandedReferencesMethods'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MethodExpandedReferencesCovers'), require('./TrainingunitExpandedReferencesMethods'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.TrainingunitExpandedReferences = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.MethodExpandedReferencesCovers, root.MartialartsTracker.TrainingunitExpandedReferencesMethods);
  }
}(this, function(ApiClient, MethodExpandedReferencesCovers, TrainingunitExpandedReferencesMethods) {
  'use strict';




  /**
   * The TrainingunitExpandedReferences model module.
   * @module model/TrainingunitExpandedReferences
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>TrainingunitExpandedReferences</code>.
   * @alias module:model/TrainingunitExpandedReferences
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TrainingunitExpandedReferences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainingunitExpandedReferences} obj Optional instance to populate.
   * @return {module:model/TrainingunitExpandedReferences} The populated <code>TrainingunitExpandedReferences</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('exercises')) {
        obj['exercises'] = MethodExpandedReferencesCovers.constructFromObject(data['exercises']);
      }
      if (data.hasOwnProperty('methods')) {
        obj['methods'] = TrainingunitExpandedReferencesMethods.constructFromObject(data['methods']);
      }
      if (data.hasOwnProperty('techniques')) {
        obj['techniques'] = MethodExpandedReferencesCovers.constructFromObject(data['techniques']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/MethodExpandedReferencesCovers} exercises
   */
  exports.prototype['exercises'] = undefined;
  /**
   * @member {module:model/TrainingunitExpandedReferencesMethods} methods
   */
  exports.prototype['methods'] = undefined;
  /**
   * @member {module:model/MethodExpandedReferencesCovers} techniques
   */
  exports.prototype['techniques'] = undefined;



  return exports;
}));


