/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TrainingunitReferences model module.
* @module model/TrainingunitReferences
* @version 0.0.1
*/
export default class TrainingunitReferences {
    /**
    * Constructs a new <code>TrainingunitReferences</code>.
    * @alias module:model/TrainingunitReferences
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TrainingunitReferences</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TrainingunitReferences} obj Optional instance to populate.
    * @return {module:model/TrainingunitReferences} The populated <code>TrainingunitReferences</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingunitReferences();

            
            
            

            if (data.hasOwnProperty('exercises')) {
                obj['exercises'] = ApiClient.convertToType(data['exercises'], ['String']);
            }
            if (data.hasOwnProperty('methods')) {
                obj['methods'] = ApiClient.convertToType(data['methods'], ['String']);
            }
            if (data.hasOwnProperty('techniques')) {
                obj['techniques'] = ApiClient.convertToType(data['techniques'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} exercises
    */
    exercises = undefined;
    /**
    * @member {Array.<String>} methods
    */
    methods = undefined;
    /**
    * @member {Array.<String>} techniques
    */
    techniques = undefined;








}


