/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TrainingunitReferencedBy model module.
* @module model/TrainingunitReferencedBy
* @version 0.0.1
*/
export default class TrainingunitReferencedBy {
    /**
    * Constructs a new <code>TrainingunitReferencedBy</code>.
    * @alias module:model/TrainingunitReferencedBy
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TrainingunitReferencedBy</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TrainingunitReferencedBy} obj Optional instance to populate.
    * @return {module:model/TrainingunitReferencedBy} The populated <code>TrainingunitReferencedBy</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingunitReferencedBy();

            
            
            

        }
        return obj;
    }









}


