/**
 * martialarts-tracker
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Exercise', 'model/ExerciseExpanded', 'model/ExerciseReferencedBy', 'model/Method', 'model/MethodExpanded', 'model/MethodReferencedBy', 'model/Technique', 'model/TechniqueExpanded', 'model/TechniqueReferencedBy', 'model/Trainingunit', 'model/TrainingunitExpanded', 'model/TrainingunitReferencedBy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Exercise'), require('../model/ExerciseExpanded'), require('../model/ExerciseReferencedBy'), require('../model/Method'), require('../model/MethodExpanded'), require('../model/MethodReferencedBy'), require('../model/Technique'), require('../model/TechniqueExpanded'), require('../model/TechniqueReferencedBy'), require('../model/Trainingunit'), require('../model/TrainingunitExpanded'), require('../model/TrainingunitReferencedBy'));
  } else {
    // Browser globals (root is window)
    if (!root.MartialartsTracker) {
      root.MartialartsTracker = {};
    }
    root.MartialartsTracker.DefaultApi = factory(root.MartialartsTracker.ApiClient, root.MartialartsTracker.Exercise, root.MartialartsTracker.ExerciseExpanded, root.MartialartsTracker.ExerciseReferencedBy, root.MartialartsTracker.Method, root.MartialartsTracker.MethodExpanded, root.MartialartsTracker.MethodReferencedBy, root.MartialartsTracker.Technique, root.MartialartsTracker.TechniqueExpanded, root.MartialartsTracker.TechniqueReferencedBy, root.MartialartsTracker.Trainingunit, root.MartialartsTracker.TrainingunitExpanded, root.MartialartsTracker.TrainingunitReferencedBy);
  }
}(this, function(ApiClient, Exercise, ExerciseExpanded, ExerciseReferencedBy, Method, MethodExpanded, MethodReferencedBy, Technique, TechniqueExpanded, TechniqueReferencedBy, Trainingunit, TrainingunitExpanded, TrainingunitReferencedBy) {
  'use strict';

  /**
   * Default service.
   * @module api/DefaultApi
   * @version 0.0.1
   */

  /**
   * Constructs a new DefaultApi. 
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the exerciseExerciseIdDelete operation.
     * @callback module:api/DefaultApi~exerciseExerciseIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} exerciseId ID of the exercise
     * @param {module:api/DefaultApi~exerciseExerciseIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.exerciseExerciseIdDelete = function(exerciseId, callback) {
      var postBody = null;

      // verify the required parameter 'exerciseId' is set
      if (exerciseId === undefined || exerciseId === null) {
        throw new Error("Missing the required parameter 'exerciseId' when calling exerciseExerciseIdDelete");
      }


      var pathParams = {
        'exerciseId': exerciseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/exercise/{exerciseId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exerciseExerciseIdGet operation.
     * @callback module:api/DefaultApi~exerciseExerciseIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Exercise} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} exerciseId ID of the exercise
     * @param {module:api/DefaultApi~exerciseExerciseIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Exercise}
     */
    this.exerciseExerciseIdGet = function(exerciseId, callback) {
      var postBody = null;

      // verify the required parameter 'exerciseId' is set
      if (exerciseId === undefined || exerciseId === null) {
        throw new Error("Missing the required parameter 'exerciseId' when calling exerciseExerciseIdGet");
      }


      var pathParams = {
        'exerciseId': exerciseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Exercise;

      return this.apiClient.callApi(
        '/exercise/{exerciseId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exerciseExerciseIdPut operation.
     * @callback module:api/DefaultApi~exerciseExerciseIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Exercise} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} exerciseId ID of the exercise
     * @param {module:model/Exercise} body ID of the exercise
     * @param {module:api/DefaultApi~exerciseExerciseIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Exercise}
     */
    this.exerciseExerciseIdPut = function(exerciseId, body, callback) {
      var postBody = body;

      // verify the required parameter 'exerciseId' is set
      if (exerciseId === undefined || exerciseId === null) {
        throw new Error("Missing the required parameter 'exerciseId' when calling exerciseExerciseIdPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling exerciseExerciseIdPut");
      }


      var pathParams = {
        'exerciseId': exerciseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Exercise;

      return this.apiClient.callApi(
        '/exercise/{exerciseId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exerciseExpandExerciseIdGet operation.
     * @callback module:api/DefaultApi~exerciseExpandExerciseIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExerciseExpanded} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} exerciseId ID of the exercise
     * @param {module:api/DefaultApi~exerciseExpandExerciseIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExerciseExpanded}
     */
    this.exerciseExpandExerciseIdGet = function(exerciseId, callback) {
      var postBody = null;

      // verify the required parameter 'exerciseId' is set
      if (exerciseId === undefined || exerciseId === null) {
        throw new Error("Missing the required parameter 'exerciseId' when calling exerciseExpandExerciseIdGet");
      }


      var pathParams = {
        'exerciseId': exerciseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = ExerciseExpanded;

      return this.apiClient.callApi(
        '/exercise/expand/{exerciseId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exerciseGet operation.
     * @callback module:api/DefaultApi~exerciseGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Exercise>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~exerciseGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Exercise>}
     */
    this.exerciseGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Exercise];

      return this.apiClient.callApi(
        '/exercise', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exercisePost operation.
     * @callback module:api/DefaultApi~exercisePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Exercise} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Exercise} body ID of the exercise
     * @param {module:api/DefaultApi~exercisePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Exercise}
     */
    this.exercisePost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling exercisePost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Exercise;

      return this.apiClient.callApi(
        '/exercise', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the exerciseReferencedByExerciseIdGet operation.
     * @callback module:api/DefaultApi~exerciseReferencedByExerciseIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExerciseReferencedBy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} exerciseId ID of the exercise
     * @param {module:api/DefaultApi~exerciseReferencedByExerciseIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExerciseReferencedBy}
     */
    this.exerciseReferencedByExerciseIdGet = function(exerciseId, callback) {
      var postBody = null;

      // verify the required parameter 'exerciseId' is set
      if (exerciseId === undefined || exerciseId === null) {
        throw new Error("Missing the required parameter 'exerciseId' when calling exerciseReferencedByExerciseIdGet");
      }


      var pathParams = {
        'exerciseId': exerciseId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = ExerciseReferencedBy;

      return this.apiClient.callApi(
        '/exercise/referenced-by/{exerciseId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the metaSwaggerGet operation.
     * @callback module:api/DefaultApi~metaSwaggerGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~metaSwaggerGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.metaSwaggerGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/meta/swagger', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodExpandMethodIdGet operation.
     * @callback module:api/DefaultApi~methodExpandMethodIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MethodExpanded} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} methodId ID of the method
     * @param {module:api/DefaultApi~methodExpandMethodIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MethodExpanded}
     */
    this.methodExpandMethodIdGet = function(methodId, callback) {
      var postBody = null;

      // verify the required parameter 'methodId' is set
      if (methodId === undefined || methodId === null) {
        throw new Error("Missing the required parameter 'methodId' when calling methodExpandMethodIdGet");
      }


      var pathParams = {
        'methodId': methodId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = MethodExpanded;

      return this.apiClient.callApi(
        '/method/expand/{methodId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodGet operation.
     * @callback module:api/DefaultApi~methodGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Method>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~methodGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Method>}
     */
    this.methodGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Method];

      return this.apiClient.callApi(
        '/method', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodMethodIdDelete operation.
     * @callback module:api/DefaultApi~methodMethodIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} methodId ID of the method
     * @param {module:api/DefaultApi~methodMethodIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.methodMethodIdDelete = function(methodId, callback) {
      var postBody = null;

      // verify the required parameter 'methodId' is set
      if (methodId === undefined || methodId === null) {
        throw new Error("Missing the required parameter 'methodId' when calling methodMethodIdDelete");
      }


      var pathParams = {
        'methodId': methodId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/method/{methodId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodMethodIdGet operation.
     * @callback module:api/DefaultApi~methodMethodIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Method} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} methodId ID of the method
     * @param {module:api/DefaultApi~methodMethodIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Method}
     */
    this.methodMethodIdGet = function(methodId, callback) {
      var postBody = null;

      // verify the required parameter 'methodId' is set
      if (methodId === undefined || methodId === null) {
        throw new Error("Missing the required parameter 'methodId' when calling methodMethodIdGet");
      }


      var pathParams = {
        'methodId': methodId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Method;

      return this.apiClient.callApi(
        '/method/{methodId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodMethodIdPut operation.
     * @callback module:api/DefaultApi~methodMethodIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Method} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} methodId ID of the method
     * @param {module:model/Method} body ID of the method
     * @param {module:api/DefaultApi~methodMethodIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Method}
     */
    this.methodMethodIdPut = function(methodId, body, callback) {
      var postBody = body;

      // verify the required parameter 'methodId' is set
      if (methodId === undefined || methodId === null) {
        throw new Error("Missing the required parameter 'methodId' when calling methodMethodIdPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling methodMethodIdPut");
      }


      var pathParams = {
        'methodId': methodId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Method;

      return this.apiClient.callApi(
        '/method/{methodId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodPost operation.
     * @callback module:api/DefaultApi~methodPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Method} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Method} body ID of the method
     * @param {module:api/DefaultApi~methodPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Method}
     */
    this.methodPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling methodPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Method;

      return this.apiClient.callApi(
        '/method', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the methodReferencedByMethodIdGet operation.
     * @callback module:api/DefaultApi~methodReferencedByMethodIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MethodReferencedBy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} methodId ID of the method
     * @param {module:api/DefaultApi~methodReferencedByMethodIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MethodReferencedBy}
     */
    this.methodReferencedByMethodIdGet = function(methodId, callback) {
      var postBody = null;

      // verify the required parameter 'methodId' is set
      if (methodId === undefined || methodId === null) {
        throw new Error("Missing the required parameter 'methodId' when calling methodReferencedByMethodIdGet");
      }


      var pathParams = {
        'methodId': methodId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = MethodReferencedBy;

      return this.apiClient.callApi(
        '/method/referenced-by/{methodId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueExpandTechniqueIdGet operation.
     * @callback module:api/DefaultApi~techniqueExpandTechniqueIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TechniqueExpanded} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} techniqueId ID of the technique
     * @param {module:api/DefaultApi~techniqueExpandTechniqueIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TechniqueExpanded}
     */
    this.techniqueExpandTechniqueIdGet = function(techniqueId, callback) {
      var postBody = null;

      // verify the required parameter 'techniqueId' is set
      if (techniqueId === undefined || techniqueId === null) {
        throw new Error("Missing the required parameter 'techniqueId' when calling techniqueExpandTechniqueIdGet");
      }


      var pathParams = {
        'techniqueId': techniqueId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TechniqueExpanded;

      return this.apiClient.callApi(
        '/technique/expand/{techniqueId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueGet operation.
     * @callback module:api/DefaultApi~techniqueGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Technique>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~techniqueGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Technique>}
     */
    this.techniqueGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Technique];

      return this.apiClient.callApi(
        '/technique', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniquePost operation.
     * @callback module:api/DefaultApi~techniquePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Technique} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Technique} body ID of the technique
     * @param {module:api/DefaultApi~techniquePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Technique}
     */
    this.techniquePost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling techniquePost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Technique;

      return this.apiClient.callApi(
        '/technique', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueReferencedByTechniqueIdGet operation.
     * @callback module:api/DefaultApi~techniqueReferencedByTechniqueIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TechniqueReferencedBy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} techniqueId ID of the technique
     * @param {module:api/DefaultApi~techniqueReferencedByTechniqueIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TechniqueReferencedBy}
     */
    this.techniqueReferencedByTechniqueIdGet = function(techniqueId, callback) {
      var postBody = null;

      // verify the required parameter 'techniqueId' is set
      if (techniqueId === undefined || techniqueId === null) {
        throw new Error("Missing the required parameter 'techniqueId' when calling techniqueReferencedByTechniqueIdGet");
      }


      var pathParams = {
        'techniqueId': techniqueId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TechniqueReferencedBy;

      return this.apiClient.callApi(
        '/technique/referenced-by/{techniqueId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueTechniqueIdDelete operation.
     * @callback module:api/DefaultApi~techniqueTechniqueIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} techniqueId ID of the technique
     * @param {module:api/DefaultApi~techniqueTechniqueIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.techniqueTechniqueIdDelete = function(techniqueId, callback) {
      var postBody = null;

      // verify the required parameter 'techniqueId' is set
      if (techniqueId === undefined || techniqueId === null) {
        throw new Error("Missing the required parameter 'techniqueId' when calling techniqueTechniqueIdDelete");
      }


      var pathParams = {
        'techniqueId': techniqueId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/technique/{techniqueId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueTechniqueIdGet operation.
     * @callback module:api/DefaultApi~techniqueTechniqueIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Technique} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} techniqueId ID of the technique
     * @param {module:api/DefaultApi~techniqueTechniqueIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Technique}
     */
    this.techniqueTechniqueIdGet = function(techniqueId, callback) {
      var postBody = null;

      // verify the required parameter 'techniqueId' is set
      if (techniqueId === undefined || techniqueId === null) {
        throw new Error("Missing the required parameter 'techniqueId' when calling techniqueTechniqueIdGet");
      }


      var pathParams = {
        'techniqueId': techniqueId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Technique;

      return this.apiClient.callApi(
        '/technique/{techniqueId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the techniqueTechniqueIdPut operation.
     * @callback module:api/DefaultApi~techniqueTechniqueIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Technique} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} techniqueId ID of the technique
     * @param {module:model/Technique} body ID of the technique
     * @param {module:api/DefaultApi~techniqueTechniqueIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Technique}
     */
    this.techniqueTechniqueIdPut = function(techniqueId, body, callback) {
      var postBody = body;

      // verify the required parameter 'techniqueId' is set
      if (techniqueId === undefined || techniqueId === null) {
        throw new Error("Missing the required parameter 'techniqueId' when calling techniqueTechniqueIdPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling techniqueTechniqueIdPut");
      }


      var pathParams = {
        'techniqueId': techniqueId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Technique;

      return this.apiClient.callApi(
        '/technique/{techniqueId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitExpandTrainingunitIdGet operation.
     * @callback module:api/DefaultApi~trainingunitExpandTrainingunitIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TrainingunitExpanded} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} trainingunitId ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitExpandTrainingunitIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TrainingunitExpanded}
     */
    this.trainingunitExpandTrainingunitIdGet = function(trainingunitId, callback) {
      var postBody = null;

      // verify the required parameter 'trainingunitId' is set
      if (trainingunitId === undefined || trainingunitId === null) {
        throw new Error("Missing the required parameter 'trainingunitId' when calling trainingunitExpandTrainingunitIdGet");
      }


      var pathParams = {
        'trainingunitId': trainingunitId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TrainingunitExpanded;

      return this.apiClient.callApi(
        '/trainingunit/expand/{trainingunitId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitGet operation.
     * @callback module:api/DefaultApi~trainingunitGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Trainingunit>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~trainingunitGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Trainingunit>}
     */
    this.trainingunitGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Trainingunit];

      return this.apiClient.callApi(
        '/trainingunit', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitPost operation.
     * @callback module:api/DefaultApi~trainingunitPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Trainingunit} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Trainingunit} body ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Trainingunit}
     */
    this.trainingunitPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling trainingunitPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Trainingunit;

      return this.apiClient.callApi(
        '/trainingunit', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitReferencedByTrainingunitIdGet operation.
     * @callback module:api/DefaultApi~trainingunitReferencedByTrainingunitIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TrainingunitReferencedBy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} trainingunitId ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitReferencedByTrainingunitIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TrainingunitReferencedBy}
     */
    this.trainingunitReferencedByTrainingunitIdGet = function(trainingunitId, callback) {
      var postBody = null;

      // verify the required parameter 'trainingunitId' is set
      if (trainingunitId === undefined || trainingunitId === null) {
        throw new Error("Missing the required parameter 'trainingunitId' when calling trainingunitReferencedByTrainingunitIdGet");
      }


      var pathParams = {
        'trainingunitId': trainingunitId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = TrainingunitReferencedBy;

      return this.apiClient.callApi(
        '/trainingunit/referenced-by/{trainingunitId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitTrainingunitIdDelete operation.
     * @callback module:api/DefaultApi~trainingunitTrainingunitIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} trainingunitId ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitTrainingunitIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.trainingunitTrainingunitIdDelete = function(trainingunitId, callback) {
      var postBody = null;

      // verify the required parameter 'trainingunitId' is set
      if (trainingunitId === undefined || trainingunitId === null) {
        throw new Error("Missing the required parameter 'trainingunitId' when calling trainingunitTrainingunitIdDelete");
      }


      var pathParams = {
        'trainingunitId': trainingunitId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/trainingunit/{trainingunitId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitTrainingunitIdGet operation.
     * @callback module:api/DefaultApi~trainingunitTrainingunitIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Trainingunit} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} trainingunitId ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitTrainingunitIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Trainingunit}
     */
    this.trainingunitTrainingunitIdGet = function(trainingunitId, callback) {
      var postBody = null;

      // verify the required parameter 'trainingunitId' is set
      if (trainingunitId === undefined || trainingunitId === null) {
        throw new Error("Missing the required parameter 'trainingunitId' when calling trainingunitTrainingunitIdGet");
      }


      var pathParams = {
        'trainingunitId': trainingunitId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Trainingunit;

      return this.apiClient.callApi(
        '/trainingunit/{trainingunitId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trainingunitTrainingunitIdPut operation.
     * @callback module:api/DefaultApi~trainingunitTrainingunitIdPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Trainingunit} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} trainingunitId ID of the trainingunit
     * @param {module:model/Trainingunit} body ID of the trainingunit
     * @param {module:api/DefaultApi~trainingunitTrainingunitIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Trainingunit}
     */
    this.trainingunitTrainingunitIdPut = function(trainingunitId, body, callback) {
      var postBody = body;

      // verify the required parameter 'trainingunitId' is set
      if (trainingunitId === undefined || trainingunitId === null) {
        throw new Error("Missing the required parameter 'trainingunitId' when calling trainingunitTrainingunitIdPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling trainingunitTrainingunitIdPut");
      }


      var pathParams = {
        'trainingunitId': trainingunitId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = Trainingunit;

      return this.apiClient.callApi(
        '/trainingunit/{trainingunitId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
